version: '3'

services:
  reverse-proxy:
    image: traefik:v2.4
    # command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker-files/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./docker-files/certs:/etc/certs
  php:
    build: ./docker-files/php
    volumes:
      - ./:/var/www/html
      - ./docker-files/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - mariadb
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro
      - ./docker-files/mysql:/var/lib/mysql
  db_admin:
    image: phpmyadmin
    ports:
      - '9000:80'
    environment:
      PMA_HOST: mariadb
    links:
      - mariadb
  nginx:
    image: nginx:1.19
    labels:
      # - "traefik.http.routers.nginx-a.rule=Host(${DOMAIN})"
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`${WP_DOMAIN}`)"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    volumes:
      - ./:/var/www/html
      - ./docker-files/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  cert:
    build: ./docker-files/services/cert
    environment:
      DOMAIN: "${WP_DOMAIN}"
    volumes:
      - ./docker-files/certs:/app

volumes:
  certs:
